SecurityMonitor/Controllers/BuildingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SecurityMonitor.Models;
using Doormandondemand;
using System.Drawing;
using Root.Reports;
using Microsoft.AspNet.Identity;
using PagedList;
using PagedList.Mvc;
using System.Threading.Tasks;
using System.Net;
using System.Data.Entity;
using SecurityMonitor.Workes;
using System.Net.Mail;
using Microsoft.AspNet.Identity.EntityFramework;
using System.IO;
using System.Text;
using System.Net.Mime;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.parser;
using iTextSharp.text.html.simpleparser;
using iTextSharp.tool.xml;




//TO DO: 

//12-19-2014
//this needs to be handle on while adding buildin. 
// cound should increase when adding building and decrease when deleting building

namespace SecurityMonitor.Controllers
{

    [Authorize(Roles = "Admin")]
    public class BuildingController : Controller
    {
        //DB context
        PointerdbEntities db = new PointerdbEntities();

        
        //shared_layout
        public ActionResult shared_layoutAllOpenRequests()
        {
            var Tomorrow = DateTime.Today.AddDays(1);
        
            var TotalReq = db.Requests.Where(c=>c.FromDate < Tomorrow && c.ToDate >= DateTime.Today).Count();

            
            return new JsonResult { Data = TotalReq, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        //shared_layout
        public ActionResult shared_layoutnext7Requests()
        {
            var Next7 = DateTime.Today.AddDays(7);
            var Tomorrow = DateTime.Today.AddDays(1);
            var Today = DateTime.Today;

            var TotalReq = db.Requests.Where(c => c.FromDate >= Today && c.FromDate <= Next7 || c.FromDate < Today && c.ToDate >= Next7).Count();


            return new JsonResult { Data = TotalReq, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }      
        
        
        //client index
    [HttpGet]
        public ActionResult ClientIndex()
        {
            //this is for the add client partial view
            ViewBag.ClientModel = new ClientsVM();
            
        
        var ObjClients = new ClientsVM();
        ObjClients.ListOfClients = db.Clients
               .Select(c => new ClientsVM
               {
                   ID = c.ID,
                   ClientName = c.ClientName,
                   BuildingCount = (int)c.BuildingCount,
                   Address = c.Address,
                    Phone =c.Phone,
                     city=c.City,
                      State = c.State,
                      zipcode = c.ZipCode,
                       Fax = c.Fax,
                       Email = c.Email
                    
                  
               }).Take(10).ToList();

        ObjClients.States = db.States.Select(c => new State { value = c.State, myState = c.State }).ToList();

        foreach (var item in ObjClients.ListOfClients)
            {
                if (item.BuildingCount <=0)
                {
                    item.BuildingCount = 0;
                }
            };
        return View(ObjClients);
        }

        [HttpPost]
        public ActionResult ClientIndex(string ClientName)
        {

            if (ModelState.IsValid)
            {
                if (ClientName != "")
                {
                    var Client = new Clients
                    {
                        ClientName = ClientName,
                        BuildingCount = 10,

                        //TO DO: update Clients table with matching fields from ClientsVM...
                    };
                    db.Clients.Add(Client);
                    db.SaveChanges();
                }
            }


            var clients = db.Clients

              .Select(c => new ClientsVM
              {
                  ID = c.ID,
                  ClientName = c.ClientName,
                  BuildingCount = (int)c.BuildingCount
              }).Take(10).ToList();
            return View(clients);

        }

        public async Task<ActionResult> LoadingClients(int? skip)
        {
            if (skip !=null)
            {
            if (Request.IsAjaxRequest())
            {

                var clientsList=await db.Clients.OrderByDescending(c=>c.ClientName).Skip((int)skip).Take(10).Select(c=> new{ClientName=c.ClientName, id = c.ID}).ToListAsync();
               return  new JsonResult { Data = clientsList, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
               
             
            }
            }
            
            return RedirectToAction("clientsIndex");
        }


        //[HttpGet]
        //public ActionResult AddClient()
        //{


        //    return View();
        //}

        [HttpPost]
        public JsonResult AddClient(Clients model)
        {
            try 
            {

                if (ModelState.IsValid)
                {
                    db.Clients.Add(model);
                    db.SaveChanges();
                }

                var clientList = db.Clients.Select(c => new
                {
                    ClientName = c.ClientName,
                    ClientPhone = c.Phone,
                    ClientFullAddress = c.Address + " " + c.City + " " + c.State + " " + c.ZipCode,
                    ClientEmail = c.Email,
                    ClientFax = c.Fax,
                    ClientAddress = c.Address,
                    ClientCity = c.City,
                    ClientState = c.State,
                    ClientZipcode = c.ZipCode,
                    BUildingID = c.ID
                }).ToList();
                var mydata = Json(clientList);
                return new JsonResult { Data = mydata, JsonRequestBehavior = JsonRequestBehavior.AllowGet };


              
         } 
            catch(Exception e)
            {
                ViewBag.ErrorMessage = e.Message;
                return null;
            }

          
        }
        //client Edit
        [HttpGet]
        public ActionResult EditClient(int id)
        {
            var client = db.Clients.Find(id);
            return View(client);
        }

           //client Edit Post
        [HttpPost]
        public ActionResult EditClient(Clients model)
        {

            if (ModelState.IsValid)
            {
                //var client = new Clients
                //{
                //     ID =model.ID,
                //     ClientName = model.ClientName,
                //     BuildingCount = model.BuildingCount
                //};
                model.BuildingCount = 0;
                db.Clients.Attach(model);
                var Entry = db.Entry(model);
                Entry.Property(c => c.ClientName).IsModified = true;
                Entry.Property(c => c.Address).IsModified = true;
                Entry.Property(c => c.City).IsModified = true;
                Entry.Property(c => c.State).IsModified = true;
                Entry.Property(c => c.Phone).IsModified = true;
                Entry.Property(c => c.Fax).IsModified = true;
                Entry.Property(c => c.Email ).IsModified = true;
                Entry.Property(c => c.BuildingCount).IsModified = true;

                db.SaveChanges();
            }
            return RedirectToAction("ClientIndex");
        }

        //Client Delete
        [HttpGet]
        public async Task<ActionResult> deleteClient(int? id)
        {
            var client = await db.Clients.FirstOrDefaultAsync(c=>c.ID==id);

            return View(client);
        }
        //Client Delete
        [HttpPost]
        public async Task<JsonResult> deleteClient(int ClientID)
        {

            if (ModelState.IsValid)
            {
                Clients model = db.Clients.Find(ClientID);
                var client = await db.Clients.FindAsync(model.ID);
                db.Clients.Remove(client);
                await db.SaveChangesAsync();
            }
            
            var clientList = db.Clients.Select(c => new
             {
                 ClientName = c.ClientName,
                 ClientPhone = c.Phone,
                 ClientFullAddress = c.Address + " " + c.City + " " + c.State + " " + c.ZipCode,
                 ClientEmail = c.Email,
                 ClientFax = c.Fax,
                 ClientAddress = c.Address,
                 ClientCity = c.City,
                 ClientState = c.State,
                 ClientZipcode = c.ZipCode,
                 BUildingID = c.ID

             }).ToList();
            var mydata = Json(clientList);
            return new JsonResult { Data = mydata, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

        }
    [HttpGet]
        public async Task<ActionResult> BuildingIndex(int ClientID) 
        {
            ViewBag.ClientID = ClientID;
            Session["ClientID"] = ClientID;
            var building = await db.Buildings
                .Where(c => c.ClientID == ClientID)
                .Select(c => new BuildingInfoVM
                {
                    BuildingName = c.BuildingName,
                    Address = c.Address,
                    BuildingPhone = c.BuildingPhone,
                    NumberOfApart = (int)c.NumberOfApartment,
                    City = c.City,
                    States = c.State,
                    ZipCode = c.Zipcode,
                    Manager = c.Manager,
                    ClientID = (int)c.ClientID,
                    ID = c.ID
                }).ToListAsync();
            return View(building);
        }
        // GET: Building
        [HttpGet]
        public ActionResult AddBuilding(int? ClientID)
        {
           
            var building = new BuildingInfoVM();
            building.StatesList =db.States.Select(c=> new State{myState =c.State, value=c.State }).ToList();
            if (ClientID != null)
            {
                ViewBag.ClientID = ClientID;
                building.ClientID = (int)ClientID;
            }

SecurityMonitor/Views/Building/ActivityPartial.cshtml
@*@model IEnumerable<SecurityMonitor.Models.ActivityLog>*@
@model PagedList.IPagedList<SecurityMonitor.Models.ActivityLog>

@{
    ViewBag.Title = "Userprofile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm("ActivityPartial", "Building", FormMethod.Get))
{
    <div class="container">
        
        <div class="row col-md-12" style="background:lightgrey;">


            <div class="col-md-3">
               
                <h5>Search By Event</h5>
            </div>
            <div class="col-md-3">

               <h5>Search By Date</h5>
               
            </div>
            <div class="col-md-6"></div>
            </div>
       
        <div class="row col-md-12" style="background:lightgrey; height:50px;">


            <div class=" col-md-3">
               
                    <div class="input-group">
                        <span class="input-group-addon">
                            <input type="radio" id="Function">
                        </span>
                        <input type="text"  class="form-control" id="input-search">
                    </div><!-- /input-group -->
                
            </div>
            <div class=" col-md-3">
                
                    <div class="input-group">
                        <span class="input-group-addon">
                            <input type="radio" id="radio-btn-date">
                        </span>
                        <input type="text" class="form-control"  id="datetimepicker" >
                    </div><!-- /input-group -->
              
            </div>

            <div class=" col-md-3 ">
                <input type="submit" value="Search" class="btn btn-success" />

            </div>
            <div class=" col-md-3">
                
                <div class="row">


                    
                   
                </div><!-- /.row -->
            </div>

        </div>

        <div class="row col-md-12">
            <div>
                page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                of @Model.PageCount

                @if (Model.HasPreviousPage)
            {
                if (ViewBag.searchBy != null)
                {
                    var searchBy = ViewBag.searchBy;
                    var search = ViewBag.search;

                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("First", "ActivityPartial", new { page = 1, SearchBy = @searchBy, Search = @search })</li>

                        <li> @Html.ActionLink("Prev", "ActivityPartial", new { page = Model.PageNumber - 1, SearchBy = @searchBy, Search = @search })</li>
                    </ul>
                }

                else if (ViewBag.searchBy == null)
                {

                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("First", "ActivityPartial", new { page = 1})</li>

                        <li> @Html.ActionLink("Prev", "ActivityPartial", new { page = Model.PageNumber - 1 })</li>
                    </ul>
                }

            }
            else
            {
                    <ul class="pagination pagination-sm">
                        <li><a href="#">First</a></li>
                        <li><a href="#">Prev</a></li>
                    </ul>

            }
                @{
                if (ViewBag.searchBy != null)
                {
                    var searchBy = ViewBag.searchBy;
                    var search = ViewBag.search;

                    <ul class="pagination pagination-sm">
                        @for (var item = 1; item <= @Model.PageCount; item++)
                        {
                            <li><a href="ActivityPartial?page=@item&SearchBy=@searchBy&Search=@search">@item</a></li>
                        }
                    </ul>
                }
                else if (ViewBag.searchBy == null)
                {
                    var searchBy = ViewBag.searchBy;
                    var search = ViewBag.search;
                    <ul class="pagination pagination-sm">
                        @for (var item = 1; item <= @Model.PageCount; item++)
                        {
                            <li><a href="ActivityPartial?page=@item">@item</a></li>
                        }
                    </ul>
                }
                }


                @if (Model.HasNextPage)
            {
                 if (ViewBag.searchBy != null)
                {
                    var searchBy = ViewBag.searchBy;
                    var search = ViewBag.search;
                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("Next", "ActivityPartial", new { page = Model.PageNumber + 1, SearchBy = @searchBy, Search = @search })</li>

                        <li>@Html.ActionLink("Last", "ActivityPartial", new { page = Model.PageCount, SearchBy = @searchBy, Search = @search })</li>
                    </ul>
                }
                 else if (ViewBag.searchBy == null)
                {

                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("Next", "ActivityPartial", new { page = Model.PageNumber + 1 })</li>

                        <li>@Html.ActionLink("Last", "ActivityPartial", new { page = Model.PageCount })</li>
                    </ul>
                 }
                }
            else
            {
                    <ul class="pagination pagination-sm">
                        <li><a href="#">Next</a></li>
                        <li><a href="#">Last</a></li>
                    </ul>
            }
            </div>
        </div>
        <div class="row col-md-12">
            <table class="table">
                <tr>

                    <th>
                        @Html.DisplayNameFor(model => model.First().FunctionPerformed)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.First().DateCreated)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.First().Message)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
            {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.FunctionPerformed)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateCreated)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Message)
                        </td>
                        <td>
                            
                            
                            <a href="@Url.Action("Details", new { id = item.ID })">
                                Details<i class="glyphicon glyphicon-cog"> </i>
                                <span class="sr-only">See More Details</span>
                            </a>
                           
                        </td>
                    </tr>
            }

            </table>
        </div>
        <div class="row col-md-12">
            <div>
                page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                of @Model.PageCount

                @if (Model.HasPreviousPage)
            {
                if (ViewBag.searchBy != null)
                {
                    var searchBy = ViewBag.searchBy;
                    var search = ViewBag.search;

                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("First", "ActivityPartial", new { page = 1, SearchBy = @searchBy, Search = @search })</li>

                        <li> @Html.ActionLink("Prev", "ActivityPartial", new { page = Model.PageNumber - 1, SearchBy = @searchBy, Search = @search })</li>
                    </ul>
                }

                else if (ViewBag.searchBy == null)
                {

                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("First", "ActivityPartial", new { page = 1 })</li>

                        <li> @Html.ActionLink("Prev", "ActivityPartial", new { page = Model.PageNumber - 1 })</li>
                    </ul>
                }

            }
            else
            {
                    <ul class="pagination pagination-sm">
                        <li><a href="#">First</a></li>
                        <li><a href="#">Prev</a></li>
                    </ul>

            }
                @{
    if (ViewBag.searchBy != null)
    {
        var searchBy = ViewBag.searchBy;
        var search = ViewBag.search;

        <ul class="pagination pagination-sm">
            @for (var item = 1; item <= @Model.PageCount; item++)
            {
                <li><a href="ActivityPartial?page=@item&SearchBy=@searchBy&Search=@search">@item</a></li>
            }
        </ul>
    }
    else if (ViewBag.searchBy == null)
    {
        var searchBy = ViewBag.searchBy;
        var search = ViewBag.search;
        <ul class="pagination pagination-sm">
            @for (var item = 1; item <= @Model.PageCount; item++)
            {
                <li><a href="ActivityPartial?page=@item">@item</a></li>
            }
        </ul>
    }
                }


                @if (Model.HasNextPage)
            {
                if (ViewBag.searchBy != null)
                {
                    var searchBy = ViewBag.searchBy;
                    var search = ViewBag.search;
                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("Next", "ActivityPartial", new { page = Model.PageNumber + 1, SearchBy = @searchBy, Search = @search })</li>

                        <li>@Html.ActionLink("Last", "ActivityPartial", new { page = Model.PageCount, SearchBy = @searchBy, Search = @search })</li>
                    </ul>
                }
                else if (ViewBag.searchBy == null)
                {

                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("Next", "ActivityPartial", new { page = Model.PageNumber + 1 })</li>

                        <li>@Html.ActionLink("Last", "ActivityPartial", new { page = Model.PageCount })</li>
                    </ul>
                }
            }
            else
            {
                    <ul class="pagination pagination-sm">
                        <li><a href="#">Next</a></li>
                        <li><a href="#">Last</a></li>
                    </ul>
            }
            </div>
        </div>




        
    </div>
}

@section scripts
{

    <link href="~/Scripts/TimePicket/jquery.datetimepicker.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/Scripts/Pagination/jquery.twbsPagination.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/TimePicket/jquery.datetimepicker.js"></script>
    <script type="text/javascript">
            $(document).ready(function (e) {




                $('#datetimepicker').focusin(function () {
                    $('#radio-btn-date').prop("checked", true).trigger('change');
                    $('#Function').attr('checked', false);



                });

                    $('#input-search').focusin(function () {

                        $('#Function').prop("checked", true).trigger("change");
                        $('#radio-btn-date').attr('checked', false);



                    });





                //==============Datepicker settings=================================
                $('#datetimepicker').datetimepicker({
                    timepicker: false,
                    formatDate: 'y.m.d'

                });

                //=============DateTimePicker plugin settings ends====================

                //=============Radio button functions ================================
                $('#Function').change(function () {
                    //alert('yes');
                    if ($('#Function').is(':Checked'))
                    {
                        $('#input-search').attr("name", "search");
                        $('#Function').attr("name", "searchBy").val('Function');
                        $('#radio-btn-date').attr('Checked', false);

                        $('#datetimepicker').removeAttr("name");
                        //alert('yes');
                    }
                    else if (!$('#Function').is(':Checked'))
                    {
                        $('#input-search').removeAttr("name");
                        $('#Function').removeAttr("name");
                        //alert('yes');
                    }
                });

                $('#radio-btn-date').change(function () {
                    //alert('yes');
                    if ($('#radio-btn-date').is(':Checked')) {
                        $('#datetimepicker').attr("name", "search");
                        $('#radio-btn-date').attr("name", "searchBy").val('Date');
                        $('#Function').attr('Checked', false);
                        $('#input-search').removeAttr("name");
                        //alert('yes');
                    }
                    else if (!$('#radio-btn-date').is(':Checked')) {
                        $('#datetimepicker').removeAttr("name");
                        $('#radio-btn-date').removeAttr("name");
                        //alert('yes');
                    }
                });
                //===============Radio buttons functions ends==================

            });
    </script>

}   

SecurityMonitor/Views/Building/RequestHistoryIndex.cshtml
@model IEnumerable<Doormandondemand.Requests>

@{
    ViewBag.Title = "RequestHistoryIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@foreach (var item in Model)
{
    <div class="row hollow4 RequestHIndexRow">
        <div class="col-md-2 RequestHIndex">
            <h4 class="underlineclass RequestHIndexColor">Name:</h4> <a href="@Url.Action("ApartmentProfile", "Building", new { ApartmentID = item.Tenant.Apartment.ID, BuildingID = item.Tenant.Apartment.BuildingID })">@Html.DisplayFor(modelItem => item.Tenant.FirstName) @Html.DisplayFor(modelItem => item.Tenant.LastName)</a>             
            <h4 class="underlineclass RequestHIndexColor">Secret PIN:</h4> @Html.DisplayFor(modelItem => item.PIN)        
            <h4 class="underlineclass RequestHIndexColor">Settings:</h4>
            @Html.ActionLink("Edit", "Edit", new { id = item.ID })
            @Html.ActionLink("Details", "Details", new { id = item.ID })
            @Html.ActionLink("Delete", "RequestdeleteHistory", new { RequestID = item.ID })
        </div>


        <div class="col-md-8 text-center RequestHIndex">
            <h4 class="" style=" padding-bottom:10px; color:#0094ff; border-bottom:1px solid #0094ff;">Description:</h4> @Html.DisplayFor(modelItem => item.Description)
        </div>
        <div class="col-md-2 RequestHIndex">
            <h4 class="underlineclass RequestHIndexColor">Request Type:</h4> @Html.DisplayFor(modelItem => item.RequestType)
            <h4 class="underlineclass RequestHIndexColor">Start Time:</h4> @Html.DisplayFor(modelItem => item.FromDate)
            <h4 class="underlineclass RequestHIndexColor">End Time:</h4> @Html.DisplayFor(modelItem => item.ToDate)
        </div>
        </div>
}

SecurityMonitor/Views/Building/_AddClient.cshtml
@model SecurityMonitor.Models.ClientsVM
@using SecurityMonitor.Models;

<!--
    ClientName
    Address
    City
    State
    zipcode
    Fax
    Phone
    email
    int? buildingcount
    int? ContactID
-->
<!--visible on sm xs-->
@using (Html.BeginForm("AddClient", "Building", FormMethod.Post))
{
    <div class="hidden-md hidden-lg visible-sm visible-xs col-sm-12 col-xs-12    lightblue " style="min-height:300px;">

        <div class="col-sm-6 col-xs-6 "><h5>Client's Name</h5></div>
        <div class="col-sm-6 col-xs-6 "><h5>Client's Address</h5></div>
        <div class="col-sm-6 col-xs-6 ">

        @Html.TextBoxFor(model => model.ClientName, null, new { @class = "form-control ClientName ", @data_bind = "value:Name, valueUpdate:'afterkeydown'", @placeholder = "Required" })
            <div style="color:red;" data-bind="text:chrName"></div>

        </div>
        <div class="col-sm-6 col-xs-6">@Html.TextBoxFor(model => model.Address, null, new { @class = "form-control ClientName ", @data_bind = "value:Address, valueUpdate:'afterkeydown'", @placeholder = "Required" })
            <div style="color:red;" data-bind="text:chrAddress"></div>
        </div>

        <h5 class="col-sm-6 col-xs-6">City</h5>
        <h5 class="col-sm-6 col-xs-6">State</h5>
        <div class="col-sm-6 col-xs-6">  @Html.TextBoxFor(model => model.city, null, new { @class = "form-control ClientName ", @data_bind = "value:City, valueUpdate:'afterkeydown'", @placeholder = "Required" })
            <div style="color:red;" data-bind="text:chrCity"></div>
        </div>
        <div class="col-sm-6 col-xs-6">
            @{IEnumerable<State> States = Model.States;}
            @Html.DropDownList("State", new SelectList(States, "value", "myState"),"Choose State" ,new { @class = "form-control" })
        </div>
        <h5 class="col-sm-6 col-xs-6">Zipcode</h5>
        <h5 class="col-sm-6 col-xs-6">Phone</h5>
        <div class="col-sm-6 col-xs-6"> @Html.TextBoxFor(model => model.zipcode, null, new { @class = "form-control ClientName ", @data_bind = "value:Zipcode, valueUpdate:'afterkeydown'", @placeholder = "Required" })
            <div style="color:red;" data-bind="text:chrZipcode"></div>
        </div>
        <div class="col-sm-6 col-xs-6"> @Html.TextBoxFor(model => model.Phone, null, new { @class = "form-control ClientName ", @data_bind = "value:Phone, valueUpdate:'afterkeydown'", @maxlength = "10", @placeholder = "Required" })
            <div style="color:red;" data-bind="text:chrPhone"></div>
        </div>

        <h5 class="col-sm-6 col-xs-6">Fax</h5>
        <h5 class="col-sm-6 col-xs-6">Email</h5>
        <div class="col-sm-6 col-xs-6"> @Html.TextBoxFor(model => model.Fax, null, new { @class = "form-control ClientName ", @data_bind = "value:Fax, valueUpdate:'afterkeydown'", @maxlength = "10", @placeholder = "Required" })
            <div style="color:red;" data-bind="text:chrFax"></div></div>
        <div class="col-sm-6 col-xs-6"> @Html.TextBoxFor(model => model.Email, null, new { @class = "form-control ClientName ", @data_bind = "value:Email, valueUpdate:'afterkeydown'", @placeholder = "Required" })
            <div style="color:red;" data-bind="text:chrEmail"></div></div>
        
    </div>
    <div class="visible-sm visible-xs hidden-lg hidden-md col-sm-12 col-xs-12 lightblue center" style="padding-bottom:20px;
padding-top:10px; padding-left:30%;">
        <input id="submitlgmd_B" type="submit" value="Add new Client" class="form-control AddClient" style="width:60%;" />
    </div>
}

<!--visible on md lg-->
<div class="hidden-xs hidden-sm visible-md visible-lg col-md-2 col-lg-2  tile_height lightblue text-center" style="min-height:100%;">
    @using (Html.BeginForm("AddClient", "Building", FormMethod.Post))
    {
        <br />
        <h5>Client's Name</h5>
        @Html.TextBox("ClientName", null, new { @class = "form-control ClientName", @data_bind="value:Name, valueUpdate:'afterkeydown'",@placeholder="Required" })
    <div  style="color:red;"data-bind="text:chrName"></div>
        <hr />
        <h5>Client's Address</h5>
        @Html.TextBox("Address", null, new { @class = "form-control", @data_bind = "value:Address, valueUpdate:'afterkeydown'", @placeholder = "Required" })
    <div style="color:red;" data-bind="text:chrAddress"></div>
        <hr />
        <h5>City</h5>
        @Html.TextBox("city", null, new { @class = "form-control", @data_bind = "value:City, valueUpdate:'afterkeydown'", @placeholder = "Required" })
    <div style="color:red;" data-bind="text:chrCity"></div>
        <hr />
        <h5>State</h5>
        IEnumerable<State> States = Model.States;
        @Html.DropDownList("State", new SelectList(States, "value", "myState"), "Choose State", new { @class = "form-control" })
        <hr />
        <h5>Zipcode</h5>
        @Html.TextBox("zipcode", null, new { @class = "form-control", @data_bind = "value:Zipcode, valueUpdate:'afterkeydown'", @placeholder = "Required" })
    <div style="color:red;" data-bind="text:chrZipcode"></div>
        <hr />
        <h5>Phone</h5>
        @Html.TextBox("Phone", null, new { @class = "form-control", @data_bind = "value:Phone, valueUpdate:'afterkeydown'", @maxlength = "10", @placeholder = "Required" })
    <div style="color:red;" data-bind="text:chrPhone"></div>
        <hr />
        <h5>Fax</h5>
        @Html.TextBoxFor(model => model.Fax, null, new { @class = "form-control ClientName ", @data_bind = "value:Fax, valueUpdate:'afterkeydown'", @maxlength = "10", @placeholder = "Required" })
    <div style="color:red;" data-bind="text:chrFax"></div>
        <hr />
        <h5>Email</h5>
        @Html.TextBoxFor(model => model.Email, null, new { @class = "form-control ClientName ", @data_bind = "value:Email, valueUpdate:'afterkeydown'", @placeholder = "Required" })
    <div style="color:red;" data-bind="text:chrEmail"></div>
        <hr />
        <input class="btn form-control AddClient" type="submit" value="Submit" id="submitlgmd" />
    }
</div>



@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
}