SecurityMonitor/Models/UserVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SecurityMonitor.Models
{
    public class UserVM
    {
     [Key]
        public int UserID { get; set; }
        //public string FirstName { get; set; }
        //public string LastName { get; set; }
        //public string Phone { get; set; }
        //public string Address { get; set; }
        //public string City { get; set; }
        //public string State { get; set; }
        //public string Zipcode { get; set;}
        //public string Username { get; set; }
        //public string Password { get; set; }
        //public DateTime created { get; set; }
        //public string isTempPWord { get; set; }


     public IEnumerable<UserBasicInfo> UserBasicInfo { get; set; }
    }

   public class  UserBasicInfo
   {
     //public string FirstName { get; set; }
     //public string LastName { get; set; }
       public string Email { get; set; }
     //public string Role { get; set; }
     //public DateTime LastActivity { get; set; }
   }
}

SecurityMonitor/Controllers/UserVMsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Doormandondemand;
using SecurityMonitor.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using PagedList.Mvc;


namespace SecurityMonitor.Controllers
{
    public class UserVMsController : Controller
    {
        private PointerdbEntities db = new PointerdbEntities();
        
        //============================ GET: UserVMs============================
        [HttpGet]
        public ActionResult UserList(string sortOrder)
        {
            
            
            
            
            
            var currentUserID = User.Identity.GetUserId();

           



           //======================= ADD USER TO ROLE ========
            var ListOfRoles = db.AspNetRoles
                .Select(r => new { Roles = r.Name, Value = r.Id}).ToList();
            ViewBag.ListOfRoles = new SelectList(ListOfRoles, "Value", "Roles");


            ////Create a Role 
            //if (!Roles.RoleExists("Admin"))
            //    Roles.CreateRole("Admin");

            ////Assign a Role
            //if (!Roles.IsUserInRole("ctoonzofficial@gmail.com", "Admin"))
            //    Roles.AddUserToRole("ctoonzofficial@gmail.com", "Admin");
            
            //=================user activity===============================

            if (User.Identity.IsAuthenticated !=false)
            {
                //====SORTING SECTION======
                ViewBag.FunctionSortParm = String.IsNullOrEmpty(sortOrder) ? "function_desc" : "";
                ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

                string myUserID = User.Identity.GetUserId().ToString();
                var myUserActivitiesLogVM = new UserActivityLogVM();

                myUserActivitiesLogVM.UserActivites = db.UserActivityLog
                           .Where(UAL => UAL.UserID == myUserID)                         
                           .Select(UAL => new ActivityLog
                           {
                               UserID = UAL.UserID,
                               ID = UAL.ID,
                               DateCreated = UAL.DateOfEvent,
                               FunctionPerformed = UAL.FunctionPerformed,
                               Message = UAL.Message
                           }).ToList();
                ViewBag.myUserActivitiesLogVM = myUserActivitiesLogVM;

                switch (sortOrder)
                {
                    case "date_desc":
                        myUserActivitiesLogVM.UserActivites = db.UserActivityLog
                            .Where(UAL => UAL.UserID == myUserID)
                            .OrderBy(UAL => UAL.DateOfEvent)
                            .Select(UAL => new ActivityLog
                            {
                                UserID = UAL.UserID,
                                ID = UAL.ID,
                                DateCreated = UAL.DateOfEvent,
                                FunctionPerformed = UAL.FunctionPerformed,
                                Message = UAL.Message
                            }).ToList();

                        ViewBag.myUserActivitiesLogVM = myUserActivitiesLogVM;
                        break;
                    case "function_desc":
                        myUserActivitiesLogVM.UserActivites = db.UserActivityLog
                            .Where(UAL => UAL.UserID == myUserID)
                            .OrderBy(UAL => UAL.FunctionPerformed)
                            .Select(UAL => new ActivityLog
                            {
                                UserID = UAL.UserID,
                                ID = UAL.ID,
                                DateCreated = UAL.DateOfEvent,
                                FunctionPerformed = UAL.FunctionPerformed,
                                Message = UAL.Message
                            }).ToList();
                       // myUserActivitiesLogVM.UserActivites = myUserActivitiesLogVM.UserActivites.OrderBy(a => a.FunctionPerformed).ToList();
                        ViewBag.myUserActivitiesLogVM = myUserActivitiesLogVM;
                        break;

                }
               
                return View(db.AspNetUsers.AsEnumerable());

            }
          return Redirect("Home/Index");
        }
        //============================END=====================================


      
      
        //=====================UPDATE ROLE SECTION ================================
        public ActionResult UpdateRole(string UserID, string RoleID)
        {
            //======save roles assigned role========
            var myRole = new Role
           {
               UserID = UserID,
               RoleID = RoleID
           };
            if (!db.Role.ToList().Exists(exists => exists.UserID == myRole.UserID
                && exists.RoleID == myRole.RoleID))
            {
                if (ModelState.IsValid)
                {
                    db.Role.Add(myRole);
                    db.SaveChanges();
                }

                //Join table and select needed fields
                var AssignedRoleReturn = db.Role
                    .Join(db.AspNetRoles,
                    AssignedRoleTable => AssignedRoleTable.RoleID,
                    RoleTable => RoleTable.Id,
                    (AssignedRole, RoleTable) => new { ReturnedUserID = AssignedRole.UserID, ReturnedAssignedRoleName = RoleTable.Name })

                    .Where(n => n.ReturnedUserID == UserID);

                //========return a json selectlist=========
                if (HttpContext.Request.IsAjaxRequest())
                {
                    return Json(new SelectList(AssignedRoleReturn, "ReturnedUserID", " ReturnedAssignedRoleName"), JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                //Join table and select needed fields
                var AssignedRoleReturn = db.Role
                    .Join(db.AspNetRoles,
                    AssignedRoleTable => AssignedRoleTable.RoleID,
                    RoleTable => RoleTable.Id,
                    (AssignedRole, RoleTable) => new { ReturnedUserID = AssignedRole.UserID, ReturnedAssignedRoleName = RoleTable.Name })

                    .Where(n => n.ReturnedUserID == UserID);

                //========return a json selectlist=========
                if (HttpContext.Request.IsAjaxRequest())
                {
                    return Json(new SelectList(AssignedRoleReturn, "ReturnedUserID", " ReturnedAssignedRoleName"), JsonRequestBehavior.AllowGet);
                }

            }
                        return View();
        } 
     
        //==============================End ==========================


        //==========================Activity partial view ==============

        public ActionResult Userprofile(int ? page, string searchBy, string search, int? BuildingID ) 
        {
            var currentUserID = User.Identity.GetUserId();
            if (Request.HttpMethod != "GET")
            {
                page = 1; // after post reset page to 1

            }
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            //=================user activity===============================
            var myUserActivitiesLogVM = new UserActivityLogVM();
            if (User.Identity.IsAuthenticated != false)
            {
                string myUserID = User.Identity.GetUserId().ToString();
                if (page == null && searchBy != null && search != null)
                {
                    ViewBag.searchBy = searchBy;
                    ViewBag.search = search;
                }
                if (page != null && searchBy != null && search != null)
                {
                    ViewBag.searchBy = searchBy;
                    ViewBag.search = search;
                }


                //=============Search=================
                if (searchBy == "Function" )
                {
                    myUserActivitiesLogVM.UserActivites = db.UserActivityLog
                               .Where(UAL => UAL.UserID == myUserID && UAL.FunctionPerformed.Contains(search) || search==null)
                               .Select(UAL => new ActivityLog
                               {
                                   UserID = UAL.UserID,
                                   ID = UAL.ID,
                                   DateCreated = UAL.DateOfEvent,
                                   FunctionPerformed = UAL.FunctionPerformed,
                                   Message = UAL.Message
                               }).ToList();

                }

                else if (searchBy == "Date")
                {
                    DateTime myvar = new DateTime();
                    if (DateTime.TryParse(search, out myvar))
                    {
                        string actualdate = search.Substring(0, 10);
                        DateTime theTime = Convert.ToDateTime(actualdate);
                        myUserActivitiesLogVM.UserActivites = db.UserActivityLog
                                   .Where(UAL => UAL.UserID == myUserID && UAL.DateOfEvent == theTime)
                                   .Select(UAL => new ActivityLog
                                   {
                                       UserID = UAL.UserID,
                                       ID = UAL.ID,
                                       DateCreated = UAL.DateOfEvent,
                                       FunctionPerformed = UAL.FunctionPerformed,
                                       Message = UAL.Message
                                   }).ToList();
                    }
                    else 
                    {
                        ViewBag.ItisNotaDay = search;

SecurityMonitor/Views/UserVMs/UserList.cshtml
@model IEnumerable<Doormandondemand.AspNetUsers>

@{
    ViewBag.Title = "Pointer Security";
}
@{

}
<h2>4530 Broadway Apt# 3K</h2>


<div class="container">
    <div class="row col-md-12 " style="height:30px; margin-bottom:10px; ">
        <div class="col-md-12 page-header text-center">
            <h2>Dioscar's Activities</h2>
        </div>
    </div>
    <div class="row col-md-12 " style="height:60px; margin-bottom:5px; ">
        <div class="col-md-3 label label-default ">
            <h3 class="text-left">
                @Html.ActionLink("Event Performed", "Userprofile", new { sortOrder = ViewBag.FunctionSortParm })
            </h3>
        </div>
        <div class="col-md-3 label label-default ">
            <h3 class="text-left">
                @Html.ActionLink("Date Created", "Userprofile", new { sortOrder = ViewBag.DateSortParm })
            </h3>
        </div>
        <div class="col-md-6 label label-default ">
            <h3 class="text-left">
                Message
            </h3>
        </div>
    </div>
    @{ var myUserActivitiesLogVM = ViewBag.myUserActivitiesLogVM; }
    @foreach (var item in myUserActivitiesLogVM.UserActivites)
    {
        <div class="row col-md-12 " style="border-bottom:1px solid white;">
        </div>
        <div class="row col-md-12 " style="height:40px; background:#F0F0F0 ;">
            <div class="col-md-3 text-left"><p>@item.FunctionPerformed </p></div>
            <div class="col-md-3 text-left"><p>@item.DateCreated</p> </div>
            <div class="col-md-6 text-left"><p>@item.Message </p></div>
        </div>
    }
</div>






<!--==========================user information section===========================-->


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            <p>Roles</p>
        </th>
        <th>
          
        </th>
        <th>

        </th>

    </tr>

@foreach (var item in Model) {
    <tr>
        <td>

            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
           
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        
        <td>
            <p id=@item.Id>No Role Assign</p>
        </td>
        <td>
            @{//Roles Dropdown
                IEnumerable<SelectListItem> ListOfRoles = ViewBag.ListOfRoles;
                @Html.DropDownListFor(model => item.AspNetRoles, ListOfRoles,
"Choose Role", new { @class = "form-control  data-dropdown-role-class ", data_dropdown_role = item.Id, })
                
                @Html.ValidationMessageFor(model => item.AspNetRoles)
            }

        </td>
        <td>
            <button type="button" class="btn btn-default datattribute-user" data-user-value="@item.Id">Save</button>
            <button type="button" class="btn btn-default datattribute-user" data-user-value="@item.Id">Details</button>
            <button type="button" class="btn btn-success datattribute-user" data-user-value="@item.Id">Edit</button>
            <button type="button" class="btn btn-danger datattribute-user" data-user-value="@item.Id">Delete</button>
        </td>
    </tr>
}
   

</table>





<div id="page-content">content</div>
    <ul id="pagination-demo" class="pagination-sm"></ul>
    @section scripts
{
        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

        <script src="~/Scripts/Pagination/jquery.twbsPagination.js"></script>


        <script type="text/javascript">
    $(document).ready(function () {
        //======Role selector=====



        $('select').on("change", function () {
            //grabs the value assigned to  data_dropdown_role attribute
            var data_attr_dropdown = $(this).attr('data-dropdown-role');
            alert(data_attr_dropdown);
            //grabs the value from the option.. value attr
            var option_value_attr = $('option:selected', this).attr('value');
            var option_Text_attr = $('option:selected', this).text();

            //=======actionResultCall===========
            if (option_value_attr != "") {//you are inside
                $.getJSON("/UserVMs/UpdateRole/", { UserID: data_attr_dropdown, RoleID: option_value_attr }, function (data) {
                    $.each(data, function (i, Model) {
                        // Model has two properties. value and text. the Model can contain 1 or more rows
                        if (Model.Text == option_Text_attr) {
                            $('#' + data_attr_dropdown).html(Model.Text);
                        }
                    });
                    //Good place to assign the return data to the Role collumn
                });

            }
        });
        $('.datattribute-user').on('click', function () {
            var items_id = $(this).attr('data-user-value');
            alert(items_id);

        });

        //<=================Call Action that return Json data=======>
        $('.data-dropdown-role-class').change(function () {


            if ($('.data-dropdown-role-class > option:selected').attr("value") != "undefined") {



            }
        });

    });




        </script>
    }

SecurityMonitor/Views/UserVMs/_ActivityPartial.cshtml
@*@model IEnumerable<SecurityMonitor.Models.ActivityLog>*@
@model PagedList.IPagedList<SecurityMonitor.Models.ActivityLog>




@using (Html.BeginForm("userprofile", "UserVMs", FormMethod.Get))
{
    <div class="container">
        
        <div class="row col-md-12" style="background:lightgrey;">


            <div class="col-md-3">
               
                <h5>Search By Event</h5>
            </div>
            <div class="col-md-3">

               <h5>Search By Date</h5>
               
            </div>
            <div class="col-md-6"></div>
            </div>
       
        <div class="row col-md-12" style="background:lightgrey; height:50px;">


            <div class=" col-md-3">
               
                    <div class="input-group">
                        <span class="input-group-addon">
                            <input type="radio" id="Function">
                        </span>
                        <input type="text"  class="form-control" id="input-search">
                    </div><!-- /input-group -->
                
            </div>
            <div class=" col-md-3">
                
                    <div class="input-group">
                        <span class="input-group-addon">
                            <input type="radio" id="radio-btn-date">
                        </span>
                        <input type="text" class="form-control"  id="datetimepicker" >
                    </div><!-- /input-group -->
              
            </div>

            <div class=" col-md-3 ">
                <input type="submit" value="Search" class="btn btn-success" />

            </div>
            <div class=" col-md-3">
                
                <div class="row">


                    
                   
                </div><!-- /.row -->
            </div>

        </div>

        <div class="row col-md-12">
            <div>
                page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                of @Model.PageCount

                @if (Model.HasPreviousPage)
            {
                if (ViewBag.searchBy != null)
                {
                    var searchBy = ViewBag.searchBy;
                    var search = ViewBag.search;

                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("First", "Userprofile", new { page = 1, SearchBy = @searchBy, Search = @search })</li>

                        <li> @Html.ActionLink("Prev", "Userprofile", new { page = Model.PageNumber - 1, SearchBy = @searchBy, Search = @search })</li>
                    </ul>
                }

                else if (ViewBag.searchBy == null)
                {

                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("First", "Userprofile", new { page = 1})</li>

                        <li> @Html.ActionLink("Prev", "Userprofile", new { page = Model.PageNumber - 1})</li>
                    </ul>
                }

            }
            else
            {
                    <ul class="pagination pagination-sm">
                        <li><a href="#">First</a></li>
                        <li><a href="#">Prev</a></li>
                    </ul>

            }
                @{
                if (ViewBag.searchBy != null)
                {
                    var searchBy = ViewBag.searchBy;
                    var search = ViewBag.search;

                    <ul class="pagination pagination-sm">
                        @for (var item = 1; item <= @Model.PageCount; item++)
                        {
                            <li><a href="userprofile?page=@item&SearchBy=@searchBy&Search=@search">@item</a></li>
                        }
                    </ul>
                }
                else if (ViewBag.searchBy == null)
                {
                    var searchBy = ViewBag.searchBy;
                    var search = ViewBag.search;
                    <ul class="pagination pagination-sm">
                        @for (var item = 1; item <= @Model.PageCount; item++)
                        {
                            <li><a href="userprofile?page=@item">@item</a></li>
                        }
                    </ul>
                }
                }


                @if (Model.HasNextPage)
            {
                 if (ViewBag.searchBy != null)
                {
                    var searchBy = ViewBag.searchBy;
                    var search = ViewBag.search;
                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("Next", "Userprofile", new { page = Model.PageNumber + 1, SearchBy = @searchBy, Search = @search })</li>

                        <li>@Html.ActionLink("Last", "Userprofile", new { page = Model.PageCount, SearchBy = @searchBy, Search = @search })</li>
                    </ul>
                }
                 else if (ViewBag.searchBy == null)
                {

                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("Next", "Userprofile", new { page = Model.PageNumber + 1 })</li>

                        <li>@Html.ActionLink("Last", "Userprofile", new { page = Model.PageCount})</li>
                    </ul>
                 }
                }
            else
            {
                    <ul class="pagination pagination-sm">
                        <li><a href="#">Next</a></li>
                        <li><a href="#">Last</a></li>
                    </ul>
            }
            </div>
        </div>
        <div class="row col-md-12">
            <table class="table">
                <tr>

                    <th>
                        @Html.DisplayNameFor(model => model.First().FunctionPerformed)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.First().DateCreated)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.First().Message)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
            {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.FunctionPerformed)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateCreated)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Message)
                        </td>
                        <td>
                            
                            
                            <a href="@Url.Action("Details", new { id = item.ID })">
                                Details<i class="glyphicon glyphicon-cog"> </i>
                                <span class="sr-only">See More Details</span>
                            </a>
                           
                        </td>
                    </tr>
            }

            </table>
        </div>
        <div class="row col-md-12">
            <div>
                page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                of @Model.PageCount

                @if (Model.HasPreviousPage)
            {
                if (ViewBag.searchBy != null)
                {
                    var searchBy = ViewBag.searchBy;
                    var search = ViewBag.search;

                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("First", "Userprofile", new { page = 1, SearchBy = @searchBy, Search = @search })</li>

                        <li> @Html.ActionLink("Prev", "Userprofile", new { page = Model.PageNumber - 1, SearchBy = @searchBy, Search = @search })</li>
                    </ul>
                }

                else if (ViewBag.searchBy == null)
                {

                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("First", "Userprofile", new { page = 1 })</li>

                        <li> @Html.ActionLink("Prev", "Userprofile", new { page = Model.PageNumber - 1 })</li>
                    </ul>
                }

            }
            else
            {
                    <ul class="pagination pagination-sm">
                        <li><a href="#">First</a></li>
                        <li><a href="#">Prev</a></li>
                    </ul>

            }
                @{
    if (ViewBag.searchBy != null)
    {
        var searchBy = ViewBag.searchBy;
        var search = ViewBag.search;

        <ul class="pagination pagination-sm">
            @for (var item = 1; item <= @Model.PageCount; item++)
            {
                <li><a href="userprofile?page=@item&SearchBy=@searchBy&Search=@search">@item</a></li>
            }
        </ul>
    }
    else if (ViewBag.searchBy == null)
    {
        var searchBy = ViewBag.searchBy;
        var search = ViewBag.search;
        <ul class="pagination pagination-sm">
            @for (var item = 1; item <= @Model.PageCount; item++)
            {
                <li><a href="userprofile?page=@item">@item</a></li>
            }
        </ul>
    }
                }


                @if (Model.HasNextPage)
            {
                if (ViewBag.searchBy != null)
                {
                    var searchBy = ViewBag.searchBy;
                    var search = ViewBag.search;
                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("Next", "Userprofile", new { page = Model.PageNumber + 1, SearchBy = @searchBy, Search = @search })</li>

                        <li>@Html.ActionLink("Last", "Userprofile", new { page = Model.PageCount, SearchBy = @searchBy, Search = @search })</li>
                    </ul>
                }
                else if (ViewBag.searchBy == null)
                {

                    <ul class="pagination pagination-sm">
                        <li> @Html.ActionLink("Next", "Userprofile", new { page = Model.PageNumber + 1 })</li>

                        <li>@Html.ActionLink("Last", "Userprofile", new { page = Model.PageCount })</li>
                    </ul>
                }
            }
            else
            {
                    <ul class="pagination pagination-sm">
                        <li><a href="#">Next</a></li>
                        <li><a href="#">Last</a></li>
                    </ul>
            }
            </div>
        </div>




        
    </div>
}

SecurityMonitor/Views/UserVMs/_BuildingInfo.cshtml
@model SecurityMonitor.Models.BuildingInfoVM

<div>
    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BuildingName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BuildingName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.States)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.States)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfApart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfApart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BuildingPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BuildingPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manager)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manager)
        </dd>

    </dl>
</div>