SecurityMonitor/Models/ManagementBuilding.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SecurityMonitor.Models;


namespace SecurityMonitor.Models
{
    public class ManagementBuilding
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public List<ManagerVM> managerVM { get; set; }
        public ManagerVM MyManagerVM { get; set; }
        public int buildingID { get; set; }

    }
}

SecurityMonitor/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Doormandondemand;
using SecurityMonitor.Models;
using System.Web.Security;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using System.Data.Entity.Validation;


namespace SecurityMonitor.Controllers
{
    [Authorize(Roles="Admin")]
    public class ManagementController : Controller
    {
       PointerdbEntities db = new PointerdbEntities();
       public ActionResult Index()
        {

            return View();
        } 
       [HttpGet]
       public ActionResult PendingModules()
        {
            List<PendingModules> ObjPendingMoodule = db.PendingModules.ToList();

            return View(ObjPendingMoodule);
        }
       [HttpPost]
       public ActionResult approve(int BuildingID, int ListOfModuleID, string ServiceName, int PendingID)
       {
          

           Module ObjModule = new Module()
           {
               BuildingID = BuildingID,
               ListOfModuleID = ListOfModuleID,
               ServiceName = ServiceName 
           };
           db.Module.Add(ObjModule);

           PendingModules ObjPendingModule = db.PendingModules.Find(PendingID);
           db.PendingModules.Remove(ObjPendingModule);
           db.SaveChanges();
           return RedirectToAction("PendingModules"); 
       }
       [HttpPost]
       public ActionResult denied(int pendingID)
       {
           PendingModules ObjPendingModule = db.PendingModules.Find(pendingID);
           db.PendingModules.Remove(ObjPendingModule);
           db.SaveChanges();
           return RedirectToAction("PendingModules");
       }
        //================Role Management===================================================
       [HttpGet]
       public ActionResult RoleIndex()
       {
           var ObjRolesList = db.AspNetRoles.ToList();
           return View(ObjRolesList);
       }
       [HttpGet]
       public ActionResult Addrole()
       {
           var ObjRole = new AspNetRoles();
           return View(ObjRole);
       }
       [HttpPost]
       [ValidateAntiForgeryToken]
       public ActionResult Addrole(AspNetRoles model)
       {
           ApplicationDbContext context = new ApplicationDbContext();

           RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
           var roleresult = RoleManager.Create(new IdentityRole(model.Name));
           return RedirectToAction("RoleIndex");    
       }
       [HttpGet]
       public ActionResult RegisterManager() 
       {
           return View();
       }
       [HttpGet]
       public ActionResult DeleteRole(string RoleName, string RoleID)
       {
           ApplicationDbContext context = new ApplicationDbContext();
           DisplayManagerRoleDelete ObjRole = new DisplayManagerRoleDelete();
           ObjRole.MyRoles =  db.AspNetRoles.Where(c => c.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
          
           var RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
           var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
          // ObjRole.buildingmanager = db.ManagerBuilding.Where(c => c.UserID == c.Manager.ID).ToList();           
           
           List<Manager> list1 = new List<Manager>();
           List<Buildings> ListBuilding = new List<Buildings>();

          // find list all manager
           var objAllManager =  db.Manager.ToList();
          // loop through all manager
           foreach(var item in objAllManager)
           {//list of role that belong to the current user
               var ListofRoleName = userManager.GetRoles(item.AspNetUsers.Id).ToList();
              //loop through all names 
               foreach (var individualRoleName in ListofRoleName)
               {//check if the current role  matches the role passed
                   if (individualRoleName == RoleName)
                   { //if match then load manager 
                       Manager ObjManager = new Manager();
                       ObjManager = db.Manager.Find(item.AspNetUsers.Id);
                      //add manager to myManager List<>
                      // ObjRole.MyManagers.Add(ObjManager);
                       var objmb = db.ManagerBuilding.Where(c => c.UserID == item.AspNetUsers.Id).ToList();
                        foreach(var item2 in objmb)
                        {
                            ListBuilding.Add(item2.Buildings);
                        }

                      list1.Add(ObjManager);
                   }
               }
           }

           ViewBag.Managers = list1;
           ViewBag.Buildings = ListBuilding;



           return View(ObjRole);
       }
       [HttpPost]
       public ActionResult DeleteRole(AspNetRoles model, string RoleName)
       {
           var ObjRole = db.AspNetRoles.Where(c => c.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
          
           db.AspNetRoles.Remove(ObjRole);
           db.SaveChanges();
           return RedirectToAction("RoleIndex");
       }
       [HttpGet]
       public ActionResult ManageUserRoles()
       {
           ApplicationDbContext dbContextRole = new ApplicationDbContext();
           // prepopulat roles for the view dropdown
           var list = dbContextRole.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
           ViewBag.Roles = list;
           ViewBag.clientlist = db.Clients.Select(c => new SelectListItem { Text = c.ClientName, Value = c.ID.ToString() }).ToList();
           return View();
       }
       [HttpPost]
       [ValidateAntiForgeryToken]
       public ActionResult RoleAddToUser(string UserName, string RoleName, string FirstName, string LastName, string Phone)
       {
          
            ApplicationDbContext context = new ApplicationDbContext();
            PointerdbEntities db = new PointerdbEntities();

            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

            var CurrentUser = db.AspNetUsers.FirstOrDefault(c => c.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase));

            
            if (CurrentUser == null)
            {
                 ViewBag.Roles  = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
                
                ViewBag.clientlist = db.Clients.Select(c => new SelectListItem { Text = c.ClientName, Value = c.ID.ToString() }).ToList();
                ViewBag.ResultMessage = "There is no user with this Username !";
                return View("ManageUserRoles");
            }
            var currentUserID = CurrentUser.Id;
            var roleresult = UserManager.AddToRole(currentUserID, RoleName);
           
            ViewBag.ResultMessage = "Role created successfully !";

            var ObjisitManager = db.Manager.Find(currentUserID);
            Manager ObjManager = new Manager();
            if (ObjisitManager != null)
            {//update
                // ObjManager.ID = ObjisitManager.ID;
                //ObjManager.FirstName = ObjisitManager.FirstName;
                //ObjManager.LastName = ObjisitManager.LastName;
                //ObjManager.Phone = ObjisitManager.Phone;
                //db.Manager.Attach(ObjManager);
                //var Entry = db.Entry(ObjManager);
                //Entry.Property(c => c.FirstName).IsModified = true;
                //Entry.Property(c => c.LastName).IsModified = true;
                //Entry.Property(c => c.Phone).IsModified = true;
            }
            else 
            {//insert
                ObjManager.ID = currentUserID;
                ObjManager.FirstName = FirstName;
                ObjManager.LastName = LastName;
                ObjManager.Phone = Phone;
                db.Manager.Add(ObjManager);
                db.SaveChanges();
            }



           

           // prepopulat roles for the view dropdown
          ViewBag.Roles  = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
           ViewBag.clientlist = db.Clients.Select(c => new SelectListItem { Text = c.ClientName, Value = c.ID.ToString() }).ToList();
           return View("ManageUserRoles");
       }
       [Authorize(Roles = "Admin")]
       [HttpPost]
       [ValidateAntiForgeryToken]
       public ActionResult GetRoles(string UserName)
       {
           if (!string.IsNullOrWhiteSpace(UserName))
           {
               ApplicationDbContext context = new ApplicationDbContext();
               var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
               var RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
               var CurrentUser = db.AspNetUsers.FirstOrDefault(c => c.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase));

               if (CurrentUser == null)
               {
                   // prepopulat roles for the view dropdown
                   ViewBag.Roles = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
                   ViewBag.clientlist = db.Clients.Select(c => new SelectListItem { Text = c.ClientName, Value = c.ID.ToString() }).ToList();
      
                   ViewBag.ResultMessage = "There is no user with this Username !";
                   return View("ManageUserRoles");
               }
               var currentUserID = CurrentUser.Id;
               ViewBag.RolesForThisUser = UserManager.GetRoles(currentUserID);

SecurityMonitor/Views/Management/AddManager.cshtml
@model SecurityMonitor.Models.ManagerVM

@{
 
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row" style="padding:90px 0 300px 0;">
    <div class="col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-lg-6 col-md-6 col-sm-6 col-xs-6">




        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

    <div class="form-horizontal" >
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group centermypform" >
    @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
    </div>
</div>

        <div class="form-group centermypform">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centermypform">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centermypform">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centermypform">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centermypform">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>
        @{List<SelectListItem> objclientlist = (List<SelectListItem>)ViewBag.clientList;}
       
         <div class="form-group centermypform">
            @Html.Label("Client", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               
              @Html.DropDownListFor(c => c.clientID, objclientlist,"Select a client", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group centermypform">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" value="Create" class="btn btn-default form-control" style="width:280px;">Next</button>
            </div>
        </div>
        <div class="text-center" style="position:relative; left:35px;">
            @Html.ActionLink("Return to Management page", "Index")
        </div>
    </div>
        }

    </div>

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SecurityMonitor/Views/Management/ManageUserRoles.cshtml
@{
    ViewBag.Title = "ManageUserRoles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row" style="border-bottom:1px solid lightgrey;">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="position:relative; left:450px; padding-bottom:40px;">
        <h2>Manage User Roles</h2>
        @Html.ActionLink("Create New Role", "Addrole") | @Html.ActionLink("Manage User Role", "ManageUserRoles")
        
    </div>
</div>
<div class="row" style="border-bottom:1px solid lightgrey; padding-top:100px; padding-bottom:100px;">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="position:relative; left:100px">
        <h2>Role Add to User</h2>

        @using (Html.BeginForm("RoleAddToUser", "Management"))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <p>
                Username :@Html.TextBox("UserName",null , new { @class = "form-control" })
                Role Name: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select ...", new {id="myRoles", @class = "form-control" })
                <div id="myclients" style="display:none;">
                    Role Client Name: @Html.DropDownList("Clients", (IEnumerable<SelectListItem>)ViewBag.clientlist, "Select a client", new { @class = "form-control" })
                    First Name: @Html.TextBox("FirstName",null, new { @class = "form-control" })
                    Last Name:@Html.TextBox("LastName", null, new { @class = "form-control" })
                    Last Name:@Html.TextBox("Phone", null, new { @class = "form-control" })

                </div>
            </p>
    <input type="submit" class="btn btn-default" style="width:400px;" value="Save" />
        }
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="padding-left:100px;">
        <h3>Get Roles for a User</h3>
        @using (Html.BeginForm("GetRoles", "Management"))
        {
            @Html.AntiForgeryToken()
            <p>
                Username : @Html.TextBox("UserName", null, new { @class = "form-control" })
                <input type="submit" class="btn btn-default" style="width:400px;" value="Get Roles for this User" />
            </p>
        }
        @if (ViewBag.RolesForThisUser != null)
        {
            <div style="background-color:yellow;">
                <h3>Roles for this user </h3>
                <ol>
                    @foreach (string s in ViewBag.RolesForThisUser)
                    {
                        <li>@s</li>
                    }
                </ol>
            </div>
        }
    </div>
    </div>
<div class="row">
    
</div>
<div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8" style="position:relative; left:450px; padding-top:40px; padding-bottom:50px;">
        <h3>Delete A User from a Role</h3>

        @using (Html.BeginForm("DeleteRoleForUser", "Management"))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <p>
                Username : @Html.TextBox("UserName",null,new { @class = "form-control" })
                Role Name: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select ...", new {@class="form-control" })

            </p>

    <input type="submit" value="Delete this user from Role" class="btn btn-default" style="width:400px;" />
        }
    </div>
    </div>

@section scripts
{
<script src="~/Scripts/jquery-2.1.1.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
           // alert('yes');
            $('#myRoles').change(function () {
                if ($(this).val() == "Manager") {
                    $('#myclients').show();
                }
                else { $('#myclients').css("display","none")}
            });
        });
    </script>
}

SecurityMonitor/Views/Management/ManagementBuilding.cshtml
@model SecurityMonitor.Models.ManagementBuilding
@using SecurityMonitor.Models;
@{
    ViewBag.Title = "ManagementBuilding";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 headerDefault">
        <ol class="breadcrumb" style="line-height:20px;" id="clientbreadcrumbid">
            <li>@Html.ActionLink("Home", "index", "Home", null, new { @class = "breadcrumblink" })</li>
            <li>@Html.ActionLink("Client's Page", "ClientHome", "building", null, new { @class = "breadcrumblink" })</li>
            <li>@Html.ActionLink("Client's Profile", "ClientProfile", "building", new { ClientID = @ViewBag.ClientID }, new { @class = "breadcrumblink" })</li>
            <li> @Html.ActionLink((string)@ViewBag.BuildingName, "BuildingProfile", "building", new { buildingID = @Model.buildingID }, new { @class = "breadcrumblink" })</li>
            <li>Manager Management</li>
        </ol>
    </div>
</div>

<section id="addmanager">
    <div class="row" style="padding:0px 0; background:white; padding-bottom:100px; ">

      
        <div class="col-md-offset-1 col-md-4 form-group " style="border:1px solid lightgrey; height:400px; background:#f5f3f3;">

            @using (Html.BeginForm("AddManagerTobuilding", "Management"))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <section>
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 text-center">
                        <p style="font-size:20px; padding-top:20px;">Add a Building Manager</p>
                    </div>
                    @Html.TextBox("FullName", null, new { placeholder = "Full Name", @class = "form-control col-md-12 col-sm-12 col-xs-12 input-sm  ", @style = " max-width: 100%; margin-bottom: 10px; margin-top:30px; " })
                    @Html.TextBox("Email", null, new { placeholder = "Email", @class = " form-control col-md-12 col-sm-12 col-xs-12 input-sm", @style = " max-width: 100%; margin-bottom: 10px;" })
                    @Html.TextBox("Phone", null, new { placeholder = "Phone", @class = "form-control col-md-6 col-sm-6 col-xs-6 input-sm", @style = " max-width: 50%;margin-bottom: 10px;" })
                    @Html.TextBox("UserName", null, new { placeholder = "UserName", @class = "form-control col-md-6 col-sm-6 col-xs-6 input-sm", @style = "max-width: 50%; margin-bottom: 10px;" })
                    @Html.Password("Password", null, new { placeholder = "Password", @class = "form-control col-md-6 col-sm-6 col-xs-6 input-sm", @style = "max-width: 50%; margin-bottom: 10px;" })
                    @Html.Password("ConfirmPassword", null, new { placeholder = "Confirm Password", @class = "form-control col-md-6 col-sm-6 col-xs-6 input-sm", @style = "max-width: 50%; margin-bottom: 10px;" })
                    @Html.Hidden("ClientID", Model.ClientID)
                    @Html.Hidden("BuildingID", Model.buildingID)

                    <div><button type="submit" class="btn btn-default col-lg-12 col-md-12 col-sm-12 col-xs-12">Add Manager</button></div>


                </section>
            }
        </div>

        <div id="Editcontent" class="col-md-offset-1 col-md-4 form-group " style="border:1px solid lightgrey; height:400px; background:#f5f3f3; display:none;">

            @using (Html.BeginForm("AddManagerTobuilding", "Management"))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <section>
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 text-center">
                        <p style="font-size:20px; padding-top:20px;">Add a Building Manager</p>
                    </div>
                    @Html.TextBox("FullName", null, new { placeholder = "Full Name", @class = "form-control col-md-12 col-sm-12 col-xs-12 input-sm  ", @style = " max-width: 100%; margin-bottom: 10px; margin-top:30px; " })
                    @Html.TextBox("Email", null, new { placeholder = "Email", @class = " form-control col-md-12 col-sm-12 col-xs-12 input-sm", @style = " max-width: 100%; margin-bottom: 10px;" })
                    @Html.TextBox("Phone", null, new { placeholder = "Phone", @class = "form-control col-md-6 col-sm-6 col-xs-6 input-sm", @style = " max-width: 50%;margin-bottom: 10px;" })
                    @Html.TextBox("UserName", null, new { placeholder = "UserName", @class = "form-control col-md-6 col-sm-6 col-xs-6 input-sm", @style = "max-width: 50%; margin-bottom: 10px;" })
                    @Html.Password("Password", null, new { placeholder = "Password", @class = "form-control col-md-6 col-sm-6 col-xs-6 input-sm", @style = "max-width: 50%; margin-bottom: 10px;" })
                    @Html.Password("ConfirmPassword", null, new { placeholder = "Confirm Password", @class = "form-control col-md-6 col-sm-6 col-xs-6 input-sm", @style = "max-width: 50%; margin-bottom: 10px;" })
                    @Html.Hidden("ClientID", Model.ClientID)
                    @Html.Hidden("BuildingID", Model.buildingID)

                    <div><button type="submit" class="btn btn-default col-lg-12 col-md-12 col-sm-12 col-xs-12">Add Manager</button></div>


                </section>
            }
        </div>
                <div class="col-md-offset-2 col-md-4 form-group  " style="padding:20px 0 20px 0; 
                                                                                    background:#f5f3f3;
                                                                                    height:400px;
                                                                                    border:1px solid lightgrey;">
                    @{var ObjActiveManager = (ActiveManagerVM)ViewBag.Activemanager;}
                    
                    <div class="col-md-12 text-center">
                       
                    @if (ObjActiveManager != null)
                    {
                        <p>@ObjActiveManager.myManager.FirstName @ObjActiveManager.myManager.LastName @Html.ActionLink("Deactivate", "DeactivateManager",
                        new { ManagerID = @ObjActiveManager.ManagerID, BuildingID=@ObjActiveManager.BuildingID})</p>
                    }
                    else
                    {
                        <p>Currently, there is no Active Manager</p>
                    }
                    </div>
                   
                    <div class="col-md-12 scrollable" style="height:300px;">
                        @if (Model.managerVM.Count > 0)
                        {

                            foreach (var item in Model.managerVM)
                            {

                                if (ObjActiveManager != null)
                                {
                                    if (ObjActiveManager.ManagerID != item.ID)
                                    {
                                        <div class="row text-center hollow3 rowsettings_manager" style=" margin-top:10px; padding:10px 0;">
                                            Name: @item.FullName
                                            |  @Html.ActionLink("Activate", "ActivateManager", new { managerid = @item.ID, buildingid = @Model.buildingID })
                                            |  <button id="editbtn" class="btn btn-link">Edit</button>
                                            |  @Html.ActionLink("Remove", "RemoveManager", new
                                                                                        {
                                                                                            BuildingID = @Model.buildingID,
                                                                                            ClientID = @Model.ClientID,
                                                                                            ManagerID = @item.ID
                                                                                        })
                                        </div>
                                    }
                                }
                                else
                                {
                                    <div class="row text-center hollow3 rowsettings_manager" style=" margin-top:10px; padding:10px 0;">
                                        Name: @item.FullName
                                        |  @Html.ActionLink("Activate", "ActivateManager", new { managerid = @item.ID, buildingid = @Model.buildingID })
                                        |  <button id="editbtn" class="btn btn-link">Edit</button>
                                        |  @Html.ActionLink("Remove", "RemoveManager", new
                                                                                        {
                                                                                            BuildingID = @Model.buildingID,
                                                                                            ClientID = @Model.ClientID,
                                                                                            ManagerID = @item.ID
                                                                                        })
                                    </div>

                                }
                            }
                        }
                        else
                        {
                            <div class="col-md-12 text-center">There is no manager assigned to the building.</div>
                        }
                    </div>        
                </div>

        
    </div>
</section>



@section scripts
{
    
    
<link href="~/Content/Site.css" rel="stylesheet" />
    <script type="text/javascript">
       

    </script>
    
    }

SecurityMonitor/Views/Management/PendingModules.cshtml
@model IEnumerable<Doormandondemand.PendingModules>

@{
    ViewBag.Title = "PendingModules";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ServiceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Buildings.BuildingName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ListOfModule.ModuleName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ServiceName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Buildings.BuildingName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ListOfModule.ModuleName)
        </td>
        <td>
          @using(@Html.BeginForm("approve","Management",new{ ServiceName = item.ServiceName, BuildingID = item.BuildingID, ListOfModuleID = item.ListOfModuleID, PendingID = @item.ID }))
          {
            <input type="submit" value="Approve"/>
            }
            
            @Html.ActionLink("Denied", "denied", new { PendingID=item.ID }) 
        </td>
    </tr>
}

</table>